// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oieravawgunjdxdukryt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZXJhdmF3Z3VuamR4ZHVrcnl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTU4NTQsImV4cCI6MjA2NTk5MTg1NH0.5rco1oq5TkkezT-7icPr3x80qZYLlumuTiRIg4iz8tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);